services:
  app:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moje_haslo
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
